### PR TITLE
Allow requests for latest version of a resource.

### PR DESCRIPTION
**Pull request by gabehamilton**

### CODE REVIEW

**Comment by calebjacob** [comment]
@gabehamilton @arktoswb this PR would probably be good to circle back to and finish up whenever you get the chance. Let me know if you need help resolving conflicts in `hub/demo/src/components/EntryDetailsLayout.tsx` - happy to help.

**Comment by calebjacob** [comment]
@gabehamilton I just force pushed to resolve conflicts with `main`. What do we have left on the backend side before we can merge this?

**Comment by calebjacob** [comment]
I pushed a few more changes to the PR:

- Added a redirect for `/agents/namespace/name` => `/agents/namespace/name/latest`
- Added `Latest` vs `Fixed` UI treatment to make it more obvious when you're on a fixed version
- Threads now support `latest`
- If a thread is fixed to an agent version, a badge with a tooltip will be displayed to make it obvious that it's fixed to a specific version

Screenshot 2024-11-11 at 11 21 31 AM
Screenshot 2024-11-11 at 11 21 41 AM
Screenshot 2024-11-11 at 10 39 39 AM
Screenshot 2024-11-11 at 10 39 32 AM

**Review by calebjacob — APPROVED** [review]

**Comment by gabehamilton** [comment]
We will tackle local_files in a separate PR.

**Pull request merged**
